=== cslevi007/U678MF_XMLGyak/U678MF_1005/CSL_mozi1.dtd
<!ELEMENT mozi (film)+>
<!ATTLIST mozi
  xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT film (rendezo+,iro)>
<!ATTLIST film
  id CDATA #REQUIRED
  mufaj CDATA #REQUIRED>

<!ELEMENT rendezo EMPTY>
<!ATTLIST rendezo
    id CDATA #REQUIRED
    nev CDATA #REQUIRED>

<!ELEMENT iro EMPTY>
<!ATTLIST iro id CDATA #REQUIRED>

=== cslevi007/U678MF_XMLGyak/U678MF_1005/mozi1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE mozi SYSTEM "CSL_mozi1.dtd"> -->

<mozi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CSL_mozi1.xsd">
    <film id="1" mufaj="horror">
        <rendezo id="1" nev="alex"/>
        <rendezo id="2" nev="alex"/>
        <rendezo id="1" nev="Madison Ivy"/>
        <iro id="1"/>
    </film>
    <film id="2" mufaj="scifi">
        <rendezo id="3" nev="alex"/>
        <rendezo id="4" nev="alex"/>
        <rendezo id="2" nev="Madison Ivy"/>
        <iro id="2"/>
    </film>
</mozi>
