=== cslevi007/U678MF_XMLGyak/U678MF_1012/CSL_konyv1.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="konyvek">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="konyv">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="cim" />
              <xs:element type="xs:string" name="szerzo" />
              <xs:element name="szereplo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nev" />
                    <xs:element type="xs:string" name="baratja" />
                    <xs:element type="xs:short" name="szuletett" />
                    <xs:element type="xs:string" name="jellemzes" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="masikSzereplo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nev" />
                    <xs:element type="xs:short" name="szuletett" />
                    <xs:element type="xs:string" name="jellemzes" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="isbn" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cslevi007/U678MF_XMLGyak/U678MF_1012/CSL_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CSL_konyv1.xsd">
    <konyv>
        <cim>Vuk</cim>
        <szerzo>Fekete István</szerzo>

        <szereplo>
            <nev>Vuk</nev>
            <baratja>Karak</baratja>
            <szuletett>2005</szuletett>
            <jellemzes>kedves aranyos kis róka</jellemzes>
        </szereplo>

        <masikSzereplo>
            <nev>Karak</nev>
            <szuletett>1994</szuletett>
            <jellemzes>bölcs megfontolt tapasztalt róka</jellemzes>
        </masikSzereplo>
    </konyv>
    <isbn>978-3-16-148410-0</isbn>
</konyvek>
